add test target; one test is currently failing:
    time="2020-11-01T15:50:31-06:00" level=debug msg="Configuration Successfully loaded" Config File=/Users/a-dalpert/Library/ledger/config.toml prefix=Config
    --- FAIL: TestEndToEnd_MinimalConfig (0.02s)
        godbledger_node.go:34: Starting GoDBLedger with flags: --log-file=debug.test --verbosity=trace --rpc-host=127.0.0.1 --rpc-port=50051 --database=memorydb --database-location=/Users/a-dalpert/Library/ledger/ledgerdata/ledger.db
        godbledger_node.go:36: Failed to start GoDBLedger Server: fork/exec ../build/bin/godbledger: no such file or directory
    FAIL
    FAIL	github.com/darcys22/godbledger/tests	0.631s

I notice that this test is trying to:

- read config from my Library folder (which makes the tests
  non-deterministic)

- trying to invoke a cli app at a path which is not there
  possible left over from an older commit before the platform
  was included in the release folder and the built output
  moved to a 'release' folder