GH-49 adjust build flags
use the integration tag for all the integration tests
which should exclude them all when that tag is missing

use a compound constraint to further segregate:

- the mysql integration tests which are not yet working,
  they require additional investment to spin up a mysql
  db out-of-process; and

- the secure connection tests which are failing on my
  machine, likely due to pollution of test context
  between tests and my local environment:

    secure_connection_test.go:130: Node Version request
    failed: rpc error: code = Unavailable desc = connection
    error: desc = "transport: authentication handshake
    failed: x509: certificate is valid for 127.0.0.1, not 0.0.0.0"

  after running the integration test suite I see the following
  untracked files:

    Untracked files:
        godbledger/rpc/~/
        godbledger/~/
        tests/~/

  I notice that tests/~/Library/ledgerdb/config.toml contains
  configuration pointing to a data direction outside the source
  folder in my local home folder, which makes me uncertain
  which config is being used during the test

  for now I am segregating the secure tests in order to have
  a clean integration test run while I refactor the way
  test data, directory, and config is managed to improve
  isolation between test cases and the local environment